import type { Answer, MentorProfile, NotificationItem, Question, Report, User } from "./types";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Ananya Iyer",
    email: "ananya.iyer@university.edu",
    studentId: "CS22B041",
    role: "student",
    reputation: 428,
    subjects: ["Computer Science", "Mathematics"],
    badges: ["Curious Mind", "First Answer", "Top Asker"],
    avatarInitials: "AI",
    institution: "Northfield Institute of Technology",
    createdAt: hoursAgo(9000),
  },
  {
    id: "u2",
    name: "Dr. Meera Raghavan",
    email: "meera.raghavan@university.edu",
    studentId: "FAC-0192",
    role: "faculty",
    reputation: 2140,
    subjects: ["Biology", "Biotechnology"],
    badges: ["Verified Faculty", "100 Accepted Answers"],
    avatarInitials: "MR",
    institution: "Northfield Institute of Technology",
    createdAt: hoursAgo(20000),
  },
  {
    id: "u3",
    name: "Rohit Banerjee",
    email: "rohit.banerjee@university.edu",
    studentId: "EC21B117",
    role: "mentor",
    reputation: 1320,
    subjects: ["Physics", "Mathematics"],
    badges: ["Verified Mentor", "Problem Solver"],
    avatarInitials: "RB",
    institution: "Northfield Institute of Technology",
    createdAt: hoursAgo(15000),
  },
  {
    id: "u4",
    name: "Sana Qureshi",
    email: "sana.qureshi@university.edu",
    studentId: "BT22B008",
    role: "mentor",
    reputation: 980,
    subjects: ["Biotechnology", "Chemistry"],
    badges: ["Verified Mentor", "Lab Guru"],
    avatarInitials: "SQ",
    institution: "Northfield Institute of Technology",
    createdAt: hoursAgo(12000),
  },
  {
    id: "u5",
    name: "Kabir Menon",
    email: "kabir.menon@university.edu",
    studentId: "CS21B093",
    role: "mentor",
    reputation: 1545,
    subjects: ["Computer Science"],
    badges: ["Verified Mentor", "Algorithm Ace"],
    avatarInitials: "KM",
    institution: "Northfield Institute of Technology",
    createdAt: hoursAgo(14000),
  },
  {
    id: "u6",
    name: "Priya Nair",
    email: "priya.nair@university.edu",
    studentId: "PH22B055",
    role: "student",
    reputation: 212,
    subjects: ["Physics"],
    badges: ["Helpful Peer"],
    avatarInitials: "PN",
    institution: "Northfield Institute of Technology",
    createdAt: hoursAgo(5000),
  },
  {
    id: "u7",
    name: "Arjun Deshmukh",
    email: "arjun.deshmukh@university.edu",
    studentId: "CH22B031",
    role: "student",
    reputation: 156,
    subjects: ["Chemistry"],
    badges: ["Curious Mind"],
    avatarInitials: "AD",
    institution: "Northfield Institute of Technology",
    createdAt: hoursAgo(4000),
  },
  {
    id: "u8",
    name: "Admin Desk",
    email: "moderation@university.edu",
    studentId: "ADM-0001",
    role: "admin",
    reputation: 0,
    subjects: [],
    badges: ["Moderator"],
    avatarInitials: "AD",
    institution: "Northfield Institute of Technology",
    createdAt: hoursAgo(21000),
  },
];

export const mockQuestions: Question[] = [
  {
    id: "q1",
    authorId: "u1",
    title: "How does recursion work in C, and when does the stack overflow?",
    description:
      "I understand the idea of a function calling itself, but I lose track of what happens in memory. How are stack frames created for each recursive call in C, and what exactly causes a segmentation fault for deep recursion like factorial(100000)?",
    subject: "Computer Science",
    topic: "Programming Fundamentals",
    tags: ["C", "Recursion", "Memory"],
    status: "solved",
    upvotes: 64,
    views: 921,
    answerCount: 3,
    createdAt: hoursAgo(26),
  },
  {
    id: "q2",
    authorId: "u6",
    title: "How do I calculate the electric field of a point charge at a distance?",
    description:
      "Our lecture derived E = kQ/r² but I am unsure how to apply it when multiple charges are involved. Do I add the fields as scalars or vectors, and how do I handle the direction in 2D problems?",
    subject: "Physics",
    topic: "Electrostatics",
    tags: ["Electrostatics", "Coulomb Law", "Vectors"],
    status: "open",
    upvotes: 41,
    views: 540,
    answerCount: 1,
    createdAt: hoursAgo(7),
  },
  {
    id: "q3",
    authorId: "u7",
    title: "How does PCR amplify DNA in just a few hours?",
    description:
      "I know PCR has denaturation, annealing and extension steps, but I don't understand how the amount of DNA grows so fast and why we need a thermostable polymerase like Taq.",
    subject: "Biotechnology",
    topic: "Molecular Techniques",
    tags: ["PCR", "DNA", "Taq Polymerase"],
    status: "solved",
    upvotes: 58,
    views: 777,
    answerCount: 2,
    createdAt: hoursAgo(50),
  },
  {
    id: "q4",
    authorId: "u1",
    title: "What is the difference between mitosis and meiosis?",
    description:
      "Both are forms of cell division but I keep mixing up the chromosome numbers and the number of daughter cells. Is there an intuitive way to remember the differences for the exam?",
    subject: "Biology",
    topic: "Cell Division",
    tags: ["Mitosis", "Meiosis", "Genetics"],
    status: "open",
    upvotes: 37,
    views: 612,
    answerCount: 1,
    createdAt: hoursAgo(13),
  },
  {
    id: "q5",
    authorId: "u6",
    title: "Why is the hybridisation of SF6 sp3d2 and not something simpler?",
    description:
      "In inorganic chemistry we were told sulphur expands its octet. How do I predict hybridisation reliably from the steric number instead of memorising every molecule?",
    subject: "Chemistry",
    topic: "Chemical Bonding",
    tags: ["Hybridisation", "VSEPR", "Bonding"],
    status: "open",
    upvotes: 22,
    views: 310,
    answerCount: 0,
    createdAt: hoursAgo(4),
  },
  {
    id: "q6",
    authorId: "u7",
    title: "How do I find the eigenvalues of a 3x3 matrix without heavy computation?",
    description:
      "The characteristic polynomial gets messy. Are there shortcuts using the trace and determinant, and how do I check my answer quickly during a timed exam?",
    subject: "Mathematics",
    topic: "Linear Algebra",
    tags: ["Linear Algebra", "Eigenvalues", "Matrices"],
    status: "open",
    upvotes: 29,
    views: 404,
    answerCount: 0,
    createdAt: hoursAgo(2),
  },
  {
    id: "q7",
    authorId: "u1",
    title: "When should I use a hash map instead of a balanced BST?",
    description:
      "Both give fast lookups. In interviews and in DSA assignments, how do I justify the choice in terms of time complexity, ordering requirements and memory?",
    subject: "Computer Science",
    topic: "Data Structures",
    tags: ["Data Structures", "Hashing", "Trees"],
    status: "open",
    upvotes: 48,
    views: 688,
    answerCount: 1,
    createdAt: hoursAgo(31),
  },
  {
    id: "q8",
    authorId: "u6",
    title: "Why does the Michaelis-Menten curve plateau at high substrate concentration?",
    description:
      "I understand Vmax conceptually but not why adding more substrate stops helping. How does this relate to enzyme saturation and the meaning of Km?",
    subject: "Biology",
    topic: "Enzymology",
    tags: ["Enzymes", "Kinetics", "Biochemistry"],
    status: "open",
    upvotes: 19,
    views: 240,
    answerCount: 0,
    createdAt: hoursAgo(6),
  },
  {
    id: "q9",
    authorId: "u7",
    title: "How do CRISPR-Cas9 guide RNAs avoid off-target edits?",
    description:
      "Our biotech lab is designing gRNAs. What rules do we follow for specificity, and how do tools score off-target risk?",
    subject: "Biotechnology",
    topic: "Genome Editing",
    tags: ["CRISPR", "Genome Editing", "gRNA"],
    status: "open",
    upvotes: 33,
    views: 388,
    answerCount: 1,
    createdAt: hoursAgo(20),
  },
  {
    id: "q10",
    authorId: "u1",
    title: "What exactly is the physical meaning of entropy in thermodynamics?",
    description:
      "Textbooks say disorder, but that feels vague. How does the statistical definition S = k ln W connect with the classical dQ/T definition?",
    subject: "Physics",
    topic: "Thermodynamics",
    tags: ["Thermodynamics", "Entropy", "Statistical Mechanics"],
    status: "solved",
    upvotes: 52,
    views: 701,
    answerCount: 1,
    createdAt: hoursAgo(72),
  },
  {
    id: "q11",
    authorId: "u6",
    title: "How do I decide between deadlock prevention and avoidance in an OS?",
    description:
      "Banker's algorithm looks expensive. In real operating systems which strategy is used and why do textbooks still teach avoidance?",
    subject: "Computer Science",
    topic: "Operating Systems",
    tags: ["Operating Systems", "Deadlock", "Concurrency"],
    status: "open",
    upvotes: 26,
    views: 296,
    answerCount: 0,
    createdAt: hoursAgo(9),
  },
  {
    id: "q12",
    authorId: "u7",
    title: "Why is titration end point different from equivalence point?",
    description:
      "In our volumetric analysis lab the indicator changes colour slightly after the calculated equivalence point. Is this error avoidable?",
    subject: "Chemistry",
    topic: "Analytical Chemistry",
    tags: ["Titration", "Lab", "Analytical"],
    status: "open",
    upvotes: 15,
    views: 188,
    answerCount: 1,
    createdAt: hoursAgo(15),
  },
];

export const mockAnswers: Answer[] = [
  {
    id: "a1",
    questionId: "q1",
    authorId: "u5",
    content:
      "Each call to a function in C pushes a new stack frame holding its parameters, local variables and the return address. In recursion those frames stack up until a base case returns. factorial(100000) needs 100000 live frames at once; the thread stack (typically 1–8 MB) runs out and the OS raises a segmentation fault. Convert to an iterative loop, or rewrite in a tail-recursive form that the compiler can optimise with -O2.",
    isAccepted: true,
    upvotes: 44,
    createdAt: hoursAgo(24),
    replies: [
      {
        id: "r1",
        authorId: "u1",
        content: "The stack-frame picture finally made it click. Thank you!",
        createdAt: hoursAgo(23),
      },
    ],
  },
  {
    id: "a2",
    questionId: "q1",
    authorId: "u3",
    content:
      "A practical trick: print the depth as the first line of the function. Watching the depth grow and then unwind makes the call stack visible without a debugger.",
    isAccepted: false,
    upvotes: 12,
    createdAt: hoursAgo(22),
    replies: [],
  },
  {
    id: "a3",
    questionId: "q1",
    authorId: "u6",
    content:
      "Also remember that each frame's size matters. A large local array inside the recursive function will overflow far sooner than a function with two int locals.",
    isAccepted: false,
    upvotes: 8,
    createdAt: hoursAgo(20),
    replies: [],
  },
  {
    id: "a4",
    questionId: "q3",
    authorId: "u2",
    content:
      "PCR is exponential: every cycle copies both strands, so after n cycles you have roughly 2^n copies of the target region. Thirty cycles give about a billion-fold amplification. Taq polymerase comes from Thermus aquaticus and survives the 94–96 °C denaturation step, so you don't have to add fresh enzyme every cycle — that is what made automation possible.",
    isAccepted: true,
    upvotes: 51,
    createdAt: hoursAgo(48),
    replies: [],
  },
  {
    id: "a5",
    questionId: "q3",
    authorId: "u4",
    content:
      "Practical lab note: annealing temperature is usually primer Tm minus 5 °C. If you get smeared bands, raise it by 2 °C steps before changing anything else.",
    isAccepted: false,
    upvotes: 17,
    createdAt: hoursAgo(44),
    replies: [],
  },
  {
    id: "a6",
    questionId: "q2",
    authorId: "u3",
    content:
      "Electric field is a vector, so you superpose the individual fields componentwise. For each charge compute magnitude kQ/r², resolve it into x and y using the geometry, sum the components, then recombine. Direction points away from a positive source charge and toward a negative one.",
    isAccepted: false,
    upvotes: 23,
    createdAt: hoursAgo(5),
    replies: [],
  },
  {
    id: "a7",
    questionId: "q4",
    authorId: "u2",
    content:
      "Mitosis: one division, two genetically identical diploid daughter cells, used for growth and repair. Meiosis: two divisions, four genetically distinct haploid gametes, with crossing over in prophase I. Memory hook — mitosis makes copies, meiosis makes variety.",
    isAccepted: false,
    upvotes: 28,
    createdAt: hoursAgo(11),
    replies: [],
  },
  {
    id: "a8",
    questionId: "q7",
    authorId: "u5",
    content:
      "Use a hash map when you only need key lookup in average O(1) and ordering is irrelevant. Use a balanced BST when you need sorted traversal, range queries or predecessor/successor in guaranteed O(log n). Hash maps also degrade with poor hash functions and use extra memory for load factor headroom.",
    isAccepted: false,
    upvotes: 31,
    createdAt: hoursAgo(28),
    replies: [],
  },
  {
    id: "a9",
    questionId: "q10",
    authorId: "u3",
    content:
      "Both definitions agree. S = k ln W counts microstates; dS = dQ/T measures heat spread at a temperature. For an ideal gas expanding isothermally both give the same ΔS = nR ln(V2/V1). Entropy is better described as 'energy dispersal among accessible states' than as disorder.",
    isAccepted: true,
    upvotes: 39,
    createdAt: hoursAgo(70),
    replies: [],
  },
  {
    id: "a10",
    questionId: "q9",
    authorId: "u4",
    content:
      "Design a 20-nt protospacer directly upstream of an NGG PAM, keep GC content between 40–60%, and avoid homopolymer runs. Tools like CRISPOR score off-targets by mismatch count and position — mismatches in the seed region near the PAM matter most.",
    isAccepted: false,
    upvotes: 14,
    createdAt: hoursAgo(18),
    replies: [],
  },
  {
    id: "a11",
    questionId: "q12",
    authorId: "u4",
    content:
      "The equivalence point is a stoichiometric fact; the end point is what the indicator can show you. Choose an indicator whose transition range brackets the pH at equivalence and the gap becomes negligible.",
    isAccepted: false,
    upvotes: 9,
    createdAt: hoursAgo(13),
    replies: [],
  },
];

export const mockMentors: MentorProfile[] = [
  {
    id: "m1",
    userId: "u2",
    expertise: ["Biology", "Biotechnology"],
    verified: true,
    helpfulAnswers: 214,
    bio: "Faculty, Department of Life Sciences. Research in molecular genetics and enzyme kinetics.",
    responseTime: "Usually replies in 3 hours",
  },
  {
    id: "m2",
    userId: "u3",
    expertise: ["Physics", "Mathematics"],
    verified: true,
    helpfulAnswers: 168,
    bio: "Final-year student mentor for electrodynamics, thermodynamics and linear algebra tutorials.",
    responseTime: "Usually replies in 5 hours",
  },
  {
    id: "m3",
    userId: "u4",
    expertise: ["Biotechnology", "Chemistry"],
    verified: true,
    helpfulAnswers: 131,
    bio: "Lab mentor for PCR, gel electrophoresis and analytical chemistry practicals.",
    responseTime: "Usually replies in 8 hours",
  },
  {
    id: "m4",
    userId: "u5",
    expertise: ["Computer Science"],
    verified: true,
    helpfulAnswers: 196,
    bio: "Mentors data structures, operating systems and systems programming in C.",
    responseTime: "Usually replies in 2 hours",
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: "n1",
    userId: "u1",
    type: "answer",
    message: "Kabir Menon answered your question on recursion in C.",
    questionId: "q1",
    read: false,
    createdAt: hoursAgo(24),
  },
  {
    id: "n2",
    userId: "u1",
    type: "accepted",
    message: "You marked an answer as accepted. The author earned +15 reputation.",
    questionId: "q1",
    read: false,
    createdAt: hoursAgo(23),
  },
  {
    id: "n3",
    userId: "u1",
    type: "upvote",
    message: "Your question 'When should I use a hash map instead of a balanced BST?' reached 48 upvotes.",
    questionId: "q7",
    read: false,
    createdAt: hoursAgo(12),
  },
  {
    id: "n4",
    userId: "u1",
    type: "mentor",
    message: "Verified mentor Dr. Meera Raghavan responded in Biology.",
    questionId: "q4",
    read: true,
    createdAt: hoursAgo(11),
  },
  {
    id: "n5",
    userId: "u1",
    type: "similar",
    message: "A similar question was found: 'How does PCR amplify DNA in just a few hours?'",
    questionId: "q3",
    read: true,
    createdAt: hoursAgo(40),
  },
];

export const mockReports: Report[] = [
  {
    id: "rep1",
    reporterId: "u6",
    contentId: "q5",
    contentType: "question",
    excerpt: "Why is the hybridisation of SF6 sp3d2 and not something simpler?",
    reason: "Duplicate of an existing question",
    status: "pending",
    createdAt: hoursAgo(3),
  },
  {
    id: "rep2",
    reporterId: "u1",
    contentId: "a3",
    contentType: "answer",
    excerpt: "Also remember that each frame's size matters...",
    reason: "Low quality / incomplete answer",
    status: "reviewing",
    createdAt: hoursAgo(10),
  },
  {
    id: "rep3",
    reporterId: "u7",
    contentId: "a6",
    contentType: "answer",
    excerpt: "Electric field is a vector, so you superpose...",
    reason: "Suspected plagiarism from a textbook",
    status: "pending",
    createdAt: hoursAgo(18),
  },
  {
    id: "rep4",
    reporterId: "u6",
    contentId: "q11",
    contentType: "question",
    excerpt: "How do I decide between deadlock prevention and avoidance in an OS?",
    reason: "Off-topic for this institution portal",
    status: "dismissed",
    createdAt: hoursAgo(30),
  },
];

export const popularTopics = [
  { label: "Data Structures", count: 128 },
  { label: "Electrostatics", count: 96 },
  { label: "Molecular Techniques", count: 84 },
  { label: "Cell Division", count: 71 },
  { label: "Linear Algebra", count: 66 },
  { label: "Chemical Bonding", count: 59 },
  { label: "Operating Systems", count: 52 },
  { label: "Thermodynamics", count: 47 },
];
