import type {
  Answer,
  CampusResource,
  CampusTask,
  MentorProfile,
  NotificationItem,
  Question,
  Report,
  User,
} from "./types";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysFromNow = (d: number) => new Date(now + d * 86400_000).toISOString();

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Ananya Iyer",
    email: "ananya.iyer@university.edu",
    studentId: "CS22B041",
    role: "student",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    reputation: 428,
    subjects: ["Computer Science", "Mathematics"],
    badges: ["Curious Mind", "Top Asker", "Fast Learner"],
    avatarInitials: "AI",
    institution: "Northfield Institute of Technology",
    bio: "Pre-final year CS student interested in Systems Programming, Distributed Systems, and Competitive Coding.",
    createdAt: hoursAgo(9000),
  },
  {
    id: "u2",
    name: "Dr. Meera Raghavan",
    email: "meera.raghavan@university.edu",
    studentId: "FAC-0192",
    role: "faculty",
    department: "Biotechnology & Life Sciences",
    reputation: 2140,
    subjects: ["Biology", "Biotechnology", "Chemistry"],
    badges: ["Verified Faculty", "Senior Mentor", "Knowledge Curator"],
    avatarInitials: "MR",
    institution: "Northfield Institute of Technology",
    bio: "Associate Professor, Department of Biotechnology. Research focus in Molecular Biology and Bio-informatics.",
    createdAt: hoursAgo(20000),
  },
  {
    id: "u3",
    name: "Rohit Banerjee",
    email: "rohit.banerjee@university.edu",
    studentId: "EC21B117",
    role: "mentor",
    department: "Electronics & Communication",
    year: "4th Year",
    reputation: 1320,
    subjects: ["Physics", "Mathematics", "Electronics"],
    badges: ["Verified Peer Mentor", "Problem Solver", "Gold Contributor"],
    avatarInitials: "RB",
    institution: "Northfield Institute of Technology",
    bio: "Senior student mentor. Passionate about Electromagnetics, Signal Processing, and Calculus.",
    availability: "available",
    createdAt: hoursAgo(15000),
  },
  {
    id: "u4",
    name: "Sana Qureshi",
    email: "sana.qureshi@university.edu",
    studentId: "BT22B008",
    role: "mentor",
    department: "Biotechnology",
    year: "4th Year",
    reputation: 980,
    subjects: ["Biotechnology", "Chemistry", "Biology"],
    badges: ["Verified Peer Mentor", "Lab Ace"],
    avatarInitials: "SQ",
    institution: "Northfield Institute of Technology",
    bio: "Senior Biotech mentor. Available for organic reaction doubts and lab experimental methodologies.",
    availability: "in_class",
    createdAt: hoursAgo(12000),
  },
  {
    id: "u5",
    name: "Kabir Menon",
    email: "kabir.menon@university.edu",
    studentId: "CS21B093",
    role: "mentor",
    department: "Computer Science & Engineering",
    year: "4th Year",
    reputation: 1545,
    subjects: ["Computer Science", "Mathematics"],
    badges: ["Verified Peer Mentor", "Algorithm Ace", "Campus Guide"],
    avatarInitials: "KM",
    institution: "Northfield Institute of Technology",
    bio: "Senior peer mentor for Data Structures, C/C++ memory models, and Operating Systems.",
    availability: "available",
    createdAt: hoursAgo(14000),
  },
  {
    id: "u6",
    name: "Priya Nair",
    email: "priya.nair@university.edu",
    studentId: "PH22B055",
    role: "student",
    department: "Physics & Natural Sciences",
    year: "2nd Year",
    reputation: 212,
    subjects: ["Physics", "Mathematics"],
    badges: ["Helpful Peer"],
    avatarInitials: "PN",
    institution: "Northfield Institute of Technology",
    bio: "Sophomore physics major with interest in classical mechanics and electrodynamics.",
    createdAt: hoursAgo(5000),
  },
  {
    id: "u7",
    name: "Arjun Deshmukh",
    email: "arjun.deshmukh@university.edu",
    studentId: "CH22B031",
    role: "student",
    department: "Chemical Engineering",
    year: "2nd Year",
    reputation: 156,
    subjects: ["Chemistry", "Physics"],
    badges: ["Curious Mind"],
    avatarInitials: "AD",
    institution: "Northfield Institute of Technology",
    bio: "2nd Year student focusing on organic synthesis and reaction kinetics.",
    createdAt: hoursAgo(4000),
  },
  {
    id: "u8",
    name: "Dr. Arvind Swaminathan",
    email: "arvind.swami@university.edu",
    studentId: "FAC-0081",
    role: "faculty",
    department: "Computer Science & Engineering",
    reputation: 3400,
    subjects: ["Computer Science", "Mathematics"],
    badges: ["Dean of Academic Affairs", "Verified Faculty"],
    avatarInitials: "AS",
    institution: "Northfield Institute of Technology",
    bio: "Dean of Academic Affairs and Professor of Computer Science. In charge of academic audits and capstone reviews.",
    createdAt: hoursAgo(25000),
  },
  {
    id: "u9",
    name: "Admin Desk",
    email: "moderation@university.edu",
    studentId: "ADM-0001",
    role: "admin",
    department: "Campus Academic Administration",
    reputation: 0,
    subjects: [],
    badges: ["Campus Administrator", "Moderation Team"],
    avatarInitials: "AD",
    institution: "Northfield Institute of Technology",
    bio: "Central institutional administration and platform oversight for CAMPUS-Q&A.",
    createdAt: hoursAgo(21000),
  },
];

export const mockCampusResources: CampusResource[] = [
  {
    id: "res-1",
    name: "Academic Coordinator's Office",
    type: "office",
    department: "Academic Affairs",
    location: "Main Administrative Complex, 1st Floor, Room 104",
    contactPerson: "Prof. S. Ramanujam",
    email: "academics.coord@university.edu",
    phone: "Ext. 2104 / +91 44 2257 8104",
    workingHours: "Mon - Fri: 9:00 AM - 5:00 PM",
    description:
      "Handles course credit transfers, semester registration overrides, hall ticket discrepancies, and attendance condonation queries.",
    tags: ["Academics", "Registration", "Credits", "Attendance", "Hall Ticket"],
  },
  {
    id: "res-2",
    name: "Department Office - Computer Science",
    type: "office",
    department: "Computer Science & Engineering",
    location: "Alan Turing Block, 2nd Floor, Room 204",
    contactPerson: "Mr. G. Venkataraman (Staff Superintendent)",
    email: "cse.office@university.edu",
    phone: "Ext. 4100 / +91 44 2257 4100",
    workingHours: "Mon - Fri: 8:30 AM - 5:30 PM",
    description:
      "Submission of lab observation sign-offs, course add/drop approval forms, elective preference slips, and mentor allocation requests.",
    tags: ["CSE", "Lab Clearance", "Electives", "HOD", "Forms"],
  },
  {
    id: "res-3",
    name: "Final Year Capstone Project Coordinator",
    type: "coordinator",
    department: "Academic Affairs & Research",
    location: "Newton Research Block, Room 310",
    contactPerson: "Dr. K. Ramanathan",
    email: "capstone.coord@university.edu",
    phone: "Ext. 3310 / +91 44 2257 3310",
    workingHours: "Tue, Thu: 2:00 PM - 5:00 PM (Walk-ins)",
    description:
      "Oversees B.Tech and M.Tech final year project proposals, guide assignment, plagiarism review, ethics committee clearance, and review rubrics.",
    tags: ["Capstone", "Project Submission", "Proposal", "Review", "Rubrics"],
  },
  {
    id: "res-4",
    name: "Ramanujan Knowledge Centre (Central Library)",
    type: "library",
    department: "Library & Information Science",
    location: "Central Campus Quadrangle, 3-Storey Library Building",
    contactPerson: "Dr. Nalini Sharma (Chief Librarian)",
    email: "library.helpdesk@university.edu",
    phone: "Ext. 5001 / +91 44 2257 5001",
    workingHours: "Mon - Sat: 8:00 AM - 11:00 PM (24/7 during Exam Weeks)",
    description:
      "Access to IEEE Xplore, ACM Digital Library, Springer, textbooks, quiet study cabins, and thesis deposit services.",
    tags: ["Library", "IEEE", "Books", "Study Halls", "No Dues"],
  },
  {
    id: "res-5",
    name: "High Performance Computing & AI Lab",
    type: "lab",
    department: "Computer Science & Engineering",
    location: "Turing Block, Ground Floor, Lab 3",
    contactPerson: "Dr. Arvind Swaminathan / Mr. Rajesh (Lab In-charge)",
    email: "hpc.lab@university.edu",
    phone: "Ext. 4125",
    workingHours: "Mon - Sat: 8:30 AM - 9:00 PM",
    description:
      "GPU cluster access (NVIDIA A100 nodes), server SSH key provisioning, high-memory simulation nodes, and research project accounts.",
    tags: ["GPU", "AI", "Lab", "Servers", "SSH", "HPC"],
  },
  {
    id: "res-6",
    name: "Training & Career Placement Cell (T&P)",
    type: "placement",
    department: "Career Development Centre",
    location: "Student Activity Center (SAC), 1st Floor, Wing A",
    contactPerson: "Dr. V. Rajeshwari (Placement Officer)",
    email: "placements@university.edu",
    phone: "Ext. 6120 / +91 44 2257 6120",
    workingHours: "Mon - Fri: 9:00 AM - 6:00 PM",
    description:
      "Internship NOC endorsements, on-campus interview schedules, company eligibility lists, resume verification, and corporate relations.",
    tags: ["Internship", "NOC", "Placements", "Resume", "Jobs"],
  },
  {
    id: "res-7",
    name: "Student Affairs & Welfare Centre",
    type: "student_affairs",
    department: "Student Affairs",
    location: "Admin Wing B, Ground Floor",
    contactPerson: "Dean of Student Affairs Office",
    email: "studentaffairs@university.edu",
    phone: "Ext. 2050",
    workingHours: "Mon - Fri: 9:00 AM - 5:00 PM",
    description:
      "Hostel amenities, scholarships, grievance redressal, student club approvals, ID card re-issuance, and emergency assistance.",
    tags: ["Hostel", "ID Card", "Scholarship", "Welfare", "Grievance"],
  },
  {
    id: "res-8",
    name: "Peer Mentors Hub & Help Desk",
    type: "mentor",
    department: "Student Collaborative Learning",
    location: "Campus Innovation Lounge, Ground Floor",
    contactPerson: "Kabir Menon / Rohit Banerjee (Student Leads)",
    email: "peermentors@university.edu",
    phone: "Ext. 1010",
    workingHours: "Daily: 4:00 PM - 8:00 PM",
    description:
      "Drop-in peer tutoring for 1st and 2nd year subjects, coding doubt clinics, exam review circles, and urgent homework walkthroughs.",
    tags: ["Peer Tutoring", "Doubts", "Mentorship", "Study Circles"],
  },
];

export const mockTasks: CampusTask[] = [
  {
    id: "task-1",
    title: "Final Year Capstone Project Proposal Submission",
    category: "Academic Milestones",
    department: "Computer Science & Engineering",
    deadline: daysFromNow(5),
    status: "in_progress",
    description:
      "Formal submission of team proposal, problem statement, system architecture, and faculty guide approval.",
    steps: [
      {
        id: "s1",
        title: "Choose project topic & finalize team members (max 3)",
        completed: true,
        guidance: "Ensure the domain aligns with departmental thrust areas (AI, Systems, Security).",
      },
      {
        id: "s2",
        title: "Draft 4-page proposal report using institutional LaTeX template",
        completed: true,
        guidance: "Include literature survey of at least 5 IEEE/ACM papers from the last 3 years.",
      },
      {
        id: "s3",
        title: "Obtain Faculty Mentor sign-off and approval signature",
        completed: false,
        guidance: "Visit your allocated faculty guide during office hours (or send PDF via portal).",
      },
      {
        id: "s4",
        title: "Upload signed proposal PDF to Capstone Portal",
        completed: false,
        guidance: "Submission link is on ERP under Academic Modules > Capstone 2026.",
      },
      {
        id: "s5",
        title: "Confirm presentation slot for Phase-1 Review Panel",
        completed: false,
        guidance: "Panel reviews commence next Wednesday in Turing Seminar Hall 2.",
      },
    ],
  },
  {
    id: "task-2",
    title: "Odd Semester Examination Form & Fee Clearance",
    category: "Examinations",
    department: "Controller of Examinations",
    deadline: daysFromNow(12),
    status: "pending",
    description:
      "Online exam registration, elective choice verification, and examination fee payment for hall ticket release.",
    steps: [
      {
        id: "s21",
        title: "Verify attendance percentage in all enrolled courses (min 75%)",
        completed: true,
        guidance: "Check portal attendance dashboard. Contact HOD if condonation is required.",
      },
      {
        id: "s22",
        title: "Confirm Open Elective & Professional Elective course codes",
        completed: false,
        guidance: "Verify matching codes with your department advisor.",
      },
      {
        id: "s23",
        title: "Complete online examination fee payment on State Bank Collect",
        completed: false,
        guidance: "Preserve DU reference transaction number for verification.",
      },
      {
        id: "s24",
        title: "Download provisional digital Hall Ticket",
        completed: false,
        guidance: "Hall tickets will be generated 48 hours after payment reconciliation.",
      },
    ],
  },
  {
    id: "task-3",
    title: "Summer Industrial Internship NOC Clearance",
    category: "Placements & Career",
    department: "Career Development Centre",
    deadline: daysFromNow(20),
    status: "completed",
    description:
      "Mandatory No Objection Certificate (NOC) for external internships lasting more than 4 weeks.",
    steps: [
      {
        id: "s31",
        title: "Obtain formal company offer letter with stipend and duration",
        completed: true,
        guidance: "Offer letter must specify start date, end date, and remote/onsite mode.",
      },
      {
        id: "s32",
        title: "Fill NOC application form on T&P Portal",
        completed: true,
        guidance: "Attach PDF of company offer letter and parent consent letter.",
      },
      {
        id: "s33",
        title: "Department Faculty Advisor endorsement",
        completed: true,
        guidance: "Verified that academic schedule does not conflict with mid-terms.",
      },
      {
        id: "s34",
        title: "Collect sealed Dean (Academic Affairs) NOC certificate",
        completed: true,
        guidance: "Signed certificate collected from Career Centre Reception.",
      },
    ],
  },
  {
    id: "task-4",
    title: "Systems Programming Lab Record Certification",
    category: "Laboratory Work",
    department: "Computer Science & Engineering",
    deadline: daysFromNow(3),
    status: "in_progress",
    description:
      "Verification of all 10 UNIX kernel programming exercises prior to practical semester exam.",
    steps: [
      {
        id: "s41",
        title: "Complete code exercises 1 through 10 in C",
        completed: true,
        guidance: "Includes fork(), execve(), pipe(), shared memory, and posix semaphores.",
      },
      {
        id: "s42",
        title: "Print execution traces and memory profiles (Valgrind)",
        completed: true,
        guidance: "Must demonstrate zero memory leaks for assignment 8 and 9.",
      },
      {
        id: "s43",
        title: "Get peer verification from lab partner / senior mentor",
        completed: false,
        guidance: "Peer review validates code commenting and formatting standards.",
      },
      {
        id: "s44",
        title: "Obtain Course Faculty signature in record book",
        completed: false,
        guidance: "Submit during Thursday afternoon lab batch hours.",
      },
    ],
  },
];

export const mockQuestions: Question[] = [
  {
    id: "q1",
    authorId: "u1",
    title: "How does recursion work in C, and when does the stack overflow?",
    description:
      "I understand the basic idea of a function calling itself, but I lose track of what happens in memory. How are stack frames created for each recursive call in C, and what exactly causes a segmentation fault for deep recursion like factorial(100000)?",
    subject: "Computer Science",
    topic: "Programming Fundamentals & Memory",
    tags: ["C", "Recursion", "Stack Frames", "Memory"],
    status: "solved",
    upvotes: 68,
    views: 940,
    answerCount: 3,
    createdAt: hoursAgo(26),
    instantAssistance: {
      mode: "verified",
      title: "Verified Campus Knowledge Base",
      content:
        "Every function invocation pushes a new stack frame containing local variables, return address, and saved registers. In standard OS environments with an 8MB stack limit, each recursive call consumes 32–64 bytes. Exceeding ~130,000 recursive frames breaches the stack guard page, triggering SIGSEGV (Stack Overflow). For deep recursion, rewrite using tail-call optimization or an iterative loop with heap memory.",
      responseType: "verified_campus",
      concepts: [
        "Stack Frame Allocation (%rsp and %rbp in x86-64)",
        "Stack Guard Pages and SIGSEGV",
        "Tail Call Optimization (TCO)",
      ],
      hints: [
        "Inspect recursion memory with `ulimit -s` in your terminal.",
        "Check how factorial(100000) exhausts the stack compared to an iterative loop.",
      ],
    },
    notifiedHelpers: [
      { id: "u5", name: "Kabir Menon", role: "mentor", department: "Computer Science", status: "answering" },
      { id: "u8", name: "Dr. Arvind Swaminathan", role: "faculty", department: "Computer Science", status: "viewed" },
    ],
  },
  {
    id: "q2",
    authorId: "u6",
    title: "How do I calculate the electric field of multiple point charges in 2D?",
    description:
      "Our physics lecture derived E = kQ/r² for a single charge, but I get confused when combining fields from three charges placed on a triangle. Do I sum them as scalars or vectors, and how do I split the angles into x and y components properly?",
    subject: "Physics",
    topic: "Electrostatics & Vector Fields",
    tags: ["Electrostatics", "Coulomb Law", "Vectors", "Physics II"],
    status: "open",
    upvotes: 42,
    views: 560,
    answerCount: 2,
    createdAt: hoursAgo(18),
    instantAssistance: {
      mode: "ai_suggested",
      title: "AI Suggested Guidance",
      content:
        "Electric fields follow the Superposition Principle as VECTOR quantities: E_total = ∑ E_i. You must never add their magnitudes as simple scalars. For each charge: 1. Calculate magnitude |E_i| = k|q_i| / r_i². 2. Find unit vector or resolve into components: E_ix = |E_i| cos θ, E_iy = |E_i| sin θ. 3. Sum separately: E_x = ∑ E_ix and E_y = ∑ E_iy. 4. Magnitude is √(E_x² + E_y²).",
      responseType: "ai_suggested",
      concepts: ["Superposition Principle", "Coulomb Force Vectors", "Cartesian Decomposition"],
      hints: ["Draw a free-body vector diagram first at the test point before touching a calculator."],
    },
    notifiedHelpers: [
      { id: "u3", name: "Rohit Banerjee", role: "mentor", department: "Electronics & Physics", status: "notified" },
    ],
  },
  {
    id: "q3",
    authorId: "u7",
    title: "What is photosynthesis and why do dark reactions still depend on light?",
    description:
      "I know photosynthesis turns sunlight and CO2 into sugars and O2 🌱. But in textbooks they call the second stage 'Dark Reactions' (Calvin Cycle). Does that mean they only happen at night? Why are they called light-independent?",
    subject: "Biology",
    topic: "Plant Physiology & Bioenergetics",
    tags: ["Photosynthesis", "Calvin Cycle", "Chloroplast", "Biochemistry"],
    status: "solved",
    upvotes: 84,
    views: 1205,
    answerCount: 2,
    createdAt: hoursAgo(48),
    instantAssistance: {
      mode: "verified",
      title: "Quick Campus Knowledge Answer",
      content:
        "Photosynthesis is the biological process by which autotrophs convert solar photon energy into chemical energy (glucose), releasing oxygen gas 🌱.\n\nThe 'Dark Reactions' (Calvin Cycle) do NOT happen only at night! They are called 'light-independent' only because photons don't strike Calvin cycle enzymes directly. However, they rely completely on ATP and NADPH synthesized during the light-dependent reactions. In the dark, ATP and NADPH run out within minutes, stopping the Calvin cycle.",
      responseType: "quick",
    },
    notifiedHelpers: [
      { id: "u2", name: "Dr. Meera Raghavan", role: "faculty", department: "Biotechnology", status: "answering" },
      { id: "u4", name: "Sana Qureshi", role: "mentor", department: "Biotechnology", status: "viewed" },
    ],
  },
  {
    id: "q4",
    authorId: "u1",
    title: "Where do I submit my final year project proposal and what are the steps?",
    description:
      "Our team has drafted the project proposal on Smart Campus IoT. Who is the project coordinator, which venue or portal do we go to, and what approvals do we need before the deadline next week?",
    subject: "Computer Science",
    topic: "Campus Academic Navigation & Tasks",
    tags: ["Project Submission", "Coordinator", "Newton Block", "Procedure"],
    status: "solved",
    upvotes: 52,
    views: 780,
    answerCount: 2,
    createdAt: hoursAgo(14),
    instantAssistance: {
      mode: "task",
      title: "Campus Task & Navigation Guidance",
      content:
        "Here is the exact step-by-step campus submission flow for your project:\n1. Complete your 4-page proposal report using the department template.\n2. Get your faculty guide's endorsement signature.\n3. Submit the proposal PDF through ERP > Capstone Module.\n4. If you need in-person clarification, meet Dr. K. Ramanathan (Newton Research Block, Room 310, Tue/Thu 2–5 PM).",
      responseType: "task_guidance",
      campusResource: mockCampusResources[2],
      taskSteps: mockTasks[0].steps,
    },
  },
  {
    id: "q5",
    authorId: "u1",
    title: "URGENT: Segmentation fault in B-Tree deletion before lab evaluation!",
    description:
      "My lab evaluation is scheduled in 2 hours with Dr. Swaminathan. When deleting a key that requires borrowing from a right sibling, my pointer arithmetic causes a Segfault on line 184 in `btree_borrow_right()`. I have pasted the snippet below. Can any senior mentor look at this immediately?",
    subject: "Computer Science",
    topic: "Data Structures & Tree Algorithms",
    tags: ["B-Tree", "Segmentation Fault", "C++", "Urgent"],
    status: "open",
    isUrgent: true,
    upvotes: 35,
    views: 410,
    answerCount: 1,
    createdAt: hoursAgo(1),
    instantAssistance: {
      mode: "ai_suggested",
      title: "Immediate AI Assistance (Helpers Notified)",
      content:
        "⚡ Immediate AI Diagnostic: In B-Tree borrow-from-right, a common segfault occurs when accessing `parent->keys[idx]` or `sibling->children[0]` without updating the child count `num_keys` before copying pointers. Check if you shifted `child->children[child->num_keys]` before reading `sibling->children[0]`.\n\n🚨 Because you marked this URGENT, notifications have been dispatched to 3 active CS Peer Mentors and Faculty.",
      responseType: "quick",
      hints: [
        "Run under GDB: `gdb ./btree` followed by `run` and `backtrace` to pinpoint line 184.",
        "Verify `sibling->num_keys >= MIN_DEGREE` before borrowing.",
      ],
    },
    notifiedHelpers: [
      { id: "u5", name: "Kabir Menon", role: "mentor", department: "Computer Science", status: "answering" },
      { id: "u8", name: "Dr. Arvind Swaminathan", role: "faculty", department: "Computer Science", status: "notified" },
    ],
  },
  {
    id: "q6",
    authorId: "u7",
    title: "How does Polymerase Chain Reaction (PCR) amplify DNA fragments exponentially?",
    description:
      "I am preparing for tomorrow's molecular genetics test. Could someone explain the three temperature cycles (Denaturation, Annealing, Extension) and why the amplification factor is 2^n after n cycles?",
    subject: "Biotechnology",
    topic: "Molecular Biology Techniques",
    tags: ["PCR", "DNA", "Taq Polymerase", "Biotechnology"],
    status: "solved",
    upvotes: 92,
    views: 1420,
    answerCount: 2,
    createdAt: hoursAgo(72),
    instantAssistance: {
      mode: "verified",
      title: "Faculty Verified Knowledge",
      content:
        "PCR is an in-vitro enzymatic DNA amplification technique consisting of 3 thermal steps repeated for 25–35 cycles:\n1. Denaturation (94–98°C): Breaks hydrogen bonds between double-stranded DNA.\n2. Annealing (50–65°C): Sequence-specific forward and reverse primers bind to single strands.\n3. Extension (72°C): Thermostable Taq DNA Polymerase synthesizes complementary strands from dNTPs.\n\nBecause each synthesized strand serves as a template in subsequent cycles, the DNA copies double every round: Theoretical Yield = Initial Template × 2ⁿ.",
      responseType: "faculty_verified",
    },
  },
  {
    id: "q7",
    authorId: "u7",
    title: "Mechanism of crossed aldol condensation with steric hindrance and uncertain enolate",
    description:
      "When reacting 2,2-dimethylpropanal (pivalaldehyde) with 3-pentanone in basic LDA at -78°C versus ethanolic NaOH at 60°C, which enolate forms predominantly? I am confused by the kinetic versus thermodynamic enolate selectivity under strong steric hindrance.",
    subject: "Chemistry",
    topic: "Organic Synthesis & Carbonyl Mechanisms",
    tags: ["Organic Chemistry", "Aldol Condensation", "LDA", "Enolates"],
    status: "open",
    upvotes: 29,
    views: 380,
    answerCount: 1,
    createdAt: hoursAgo(8),
    instantAssistance: {
      mode: "uncertain",
      title: "AI Needs More Information — Complex Organic Mechanism",
      content:
        "⚠ This looks like an advanced Organic Synthesis selectivity problem involving bulky bases and kinetic vs thermodynamic enolate trapping. While I can explain the general principle that LDA at -78°C deprotonates the less hindered alpha-carbon (kinetic enolate), determining the diastereomeric ratio of the crossed aldol product requires verified human faculty review.",
      responseType: "ai_uncertain",
      concepts: [
        "Kinetic vs Thermodynamic Enolate Control",
        "LDA bulky amide base steric preference",
        "Zimmerman-Traxler 6-membered transition state model",
      ],
      hints: [
        "Remember that pivalaldehyde has ZERO alpha hydrogens and can only act as the electrophilic acceptor.",
        "Check Carey & Sundberg Organic Chemistry, Vol B, Chapter 1.",
      ],
      recommendedMentorId: "u4",
      recommendedFacultyId: "u2",
      humanHelpRequested: true,
    },
    notifiedHelpers: [
      { id: "u4", name: "Sana Qureshi", role: "mentor", department: "Biotechnology & Chemistry", status: "viewed" },
      { id: "u2", name: "Dr. Meera Raghavan", role: "faculty", department: "Biotechnology", status: "notified" },
    ],
  },
];

export const mockAnswers: Answer[] = [
  {
    id: "a1",
    questionId: "q1",
    authorId: "u5", // Kabir Menon (Mentor)
    content:
      "Great question Ananya! Here is how memory frames work in standard C/x86_64:\n\n1. When `foo()` is invoked, the CPU pushes `%rip` (return address), saves the old base pointer `%rbp`, and subtracts bytes from `%rsp` (stack pointer) to allocate room for local variables.\n2. For each recursive call `foo(n - 1)`, another stack frame is created on top of the call stack.\n3. The stack lives in a finite memory region (usually 8MB on Linux/macOS, check with `ulimit -s`). If your recursion does not hit a base case before exceeding 8MB, `%rsp` collides with the protected stack guard page, triggering a hardware memory fault -> `SIGSEGV` (Segmentation fault).\n\nTip for factorial(100000): In C, use an iterative loop or heap arrays (`malloc`) with a BigNum library, because 100,000 stack frames take ~4.8MB which quickly overflows with compiler debug symbols attached.",
    answerType: "peer",
    isAccepted: true,
    isFacultyVerified: true,
    verifiedBy: "u8",
    verifiedByName: "Dr. Arvind Swaminathan",
    verifiedAt: hoursAgo(20),
    upvotes: 46,
    downvotes: 0,
    createdAt: hoursAgo(24),
    replies: [
      {
        id: "r1",
        authorId: "u1",
        content: "Thank you Kabir! That completely clarifies why `ulimit` matters. I will switch to an iterative loop.",
        createdAt: hoursAgo(22),
      },
    ],
  },
  {
    id: "a2",
    questionId: "q1",
    authorId: "u8", // Dr. Swaminathan (Faculty)
    content:
      "Adding to Kabir's excellent breakdown: If you compile with `gcc -O2` or `-O3` and structure your function with tail recursion (where the recursive return is purely `return helper(acc, n - 1)` without pending operations), modern GCC will perform Tail-Call Optimization (TCO), reusing the current stack frame and running in O(1) stack space.",
    answerType: "faculty_verified",
    isAccepted: false,
    isFacultyVerified: true,
    verifiedBy: "u8",
    verifiedByName: "Dr. Arvind Swaminathan",
    verifiedAt: hoursAgo(20),
    upvotes: 38,
    downvotes: 0,
    createdAt: hoursAgo(21),
    replies: [],
  },
  {
    id: "a3",
    questionId: "q3",
    authorId: "u2", // Dr. Meera Raghavan (Faculty)
    content:
      "To clarify why historical nomenclature caused this confusion:\n\nIn 1905, Blackman first noted that photosynthesis consists of two phases: a photochemical reaction and a biochemical reaction. Later researchers termed the biochemical phase 'dark reactions'.\n\nHowever, in modern biology curricula we now call it the **Light-Independent Phase or Calvin-Benson Cycle**.\n\nKey reasons it cannot run continuously in the dark:\n1. It requires continuous supplies of ATP and NADPH produced by photophosphorylation in the thylakoid membranes.\n2. Several critical Calvin cycle enzymes (notably RuBisCO and FBPase) are light-activated via the ferredoxin-thioredoxin regulatory system. When darkness falls, these enzymes deactivate within 3–5 minutes.",
    answerType: "faculty_verified",
    isAccepted: true,
    isFacultyVerified: true,
    verifiedBy: "u2",
    verifiedByName: "Dr. Meera Raghavan",
    verifiedAt: hoursAgo(44),
    upvotes: 72,
    downvotes: 0,
    createdAt: hoursAgo(46),
    replies: [
      {
        id: "r2",
        authorId: "u7",
        content: "Understood Dr. Meera! The thioredoxin activation detail makes complete sense.",
        createdAt: hoursAgo(42),
      },
    ],
  },
  {
    id: "a4",
    questionId: "q5",
    authorId: "u5", // Kabir Menon
    content:
      "Kabir here — check line 184 right now! In `btree_borrow_right()`, you are doing:\n`child->keys[child->num_keys] = parent->keys[idx];`\nMake sure you increment `child->num_keys++` BEFORE moving the sibling's left-most child pointer `child->children[child->num_keys] = sibling->children[0];`!\nIf you do it out of order, you overwrite unallocated memory boundary.",
    answerType: "peer",
    isAccepted: false,
    upvotes: 18,
    downvotes: 0,
    createdAt: hoursAgo(0.5),
    replies: [],
  },
];

export const mockMentors: MentorProfile[] = [
  {
    id: "m1",
    userId: "u5", // Kabir Menon
    expertise: ["Computer Science", "Mathematics"],
    department: "Computer Science & Engineering",
    verified: true,
    helpfulAnswers: 86,
    answersGiven: 112,
    bio: "Senior Year CSE | Lead Peer Mentor for Algorithms, Systems & Linux. Ready to jump on urgent debugging queries.",
    responseTime: "< 30 mins",
    availability: "available",
  },
  {
    id: "m2",
    userId: "u3", // Rohit Banerjee
    expertise: ["Physics", "Mathematics", "Electronics"],
    department: "Electronics & Communication",
    verified: true,
    helpfulAnswers: 64,
    answersGiven: 88,
    bio: "Final Year ECE | Peer mentor for Electromagnetics, Circuit Analysis, and Differential Equations.",
    responseTime: "< 45 mins",
    availability: "available",
  },
  {
    id: "m3",
    userId: "u4", // Sana Qureshi
    expertise: ["Biotechnology", "Chemistry", "Biology"],
    department: "Biotechnology",
    verified: true,
    helpfulAnswers: 52,
    answersGiven: 71,
    bio: "Senior Biotech Mentor | Organic synthesis, PCR techniques, and lab protocol walk-throughs.",
    responseTime: "~ 1 hour",
    availability: "in_class",
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: "n1",
    userId: "u1",
    type: "answer",
    message: "Kabir Menon (Peer Mentor) answered your question 'How does recursion work in C?'",
    questionId: "q1",
    read: false,
    createdAt: hoursAgo(24),
  },
  {
    id: "n2",
    userId: "u1",
    type: "faculty_verification",
    message: "Dr. Arvind Swaminathan verified an answer on 'How does recursion work in C?'. It is now part of the campus knowledge base 🎓",
    questionId: "q1",
    read: false,
    createdAt: hoursAgo(20),
  },
  {
    id: "n3",
    userId: "u5",
    type: "urgent_question",
    message: "🚨 URGENT Question in Computer Science: 'Segmentation fault in B-Tree deletion before lab evaluation!' needs peer assistance.",
    questionId: "q5",
    read: false,
    createdAt: hoursAgo(1),
  },
  {
    id: "n4",
    userId: "u1",
    type: "announcement",
    message: "Campus Milestone Reminder: Capstone Project Proposals must be uploaded to ERP by Friday 5:00 PM.",
    read: true,
    createdAt: hoursAgo(36),
  },
  {
    id: "n5",
    userId: "u7",
    type: "faculty_verification",
    message: "Dr. Meera Raghavan provided a Faculty Verified explanation on your Biology doubt 🌱",
    questionId: "q3",
    read: true,
    createdAt: hoursAgo(44),
  },
];

export const mockReports: Report[] = [
  {
    id: "rep-1",
    reporterId: "u6",
    contentId: "q99",
    contentType: "question",
    excerpt: "Where can I buy leaked mid-semester exam questions for CS201?",
    reason: "misinformation",
    customDetails: "Academic integrity violation: asking for leaked test papers.",
    status: "pending",
    createdAt: hoursAgo(6),
  },
  {
    id: "rep-2",
    reporterId: "u7",
    contentId: "a99",
    contentType: "answer",
    excerpt: "Join this external Telegram channel for paid homework services bit.ly/xxx",
    reason: "spam",
    customDetails: "Commercial advertisement and spam link inside answer text.",
    status: "pending",
    createdAt: hoursAgo(12),
  },
];
