/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as MyQuestionsRouteImport } from './routes/my-questions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as QuestionsQuestionIdRouteImport } from './routes/questions.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuestionsRoute = MyQuestionsRouteImport.update({
  id: '/my-questions',
  path: '/my-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdRoute = QuestionsQuestionIdRouteImport.update({
  id: '/questions/$questionId',
  path: '/questions/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/mentors': typeof MentorsRoute
  '/moderation': typeof ModerationRoute
  '/my-questions': typeof MyQuestionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/tasks': typeof TasksRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/mentors': typeof MentorsRoute
  '/moderation': typeof ModerationRoute
  '/my-questions': typeof MyQuestionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/tasks': typeof TasksRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/mentors': typeof MentorsRoute
  '/moderation': typeof ModerationRoute
  '/my-questions': typeof MyQuestionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/tasks': typeof TasksRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/dashboard'
    | '/explore'
    | '/mentors'
    | '/moderation'
    | '/my-questions'
    | '/notifications'
    | '/profile'
    | '/resources'
    | '/saved'
    | '/tasks'
    | '/questions/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/dashboard'
    | '/explore'
    | '/mentors'
    | '/moderation'
    | '/my-questions'
    | '/notifications'
    | '/profile'
    | '/resources'
    | '/saved'
    | '/tasks'
    | '/questions/$questionId'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/dashboard'
    | '/explore'
    | '/mentors'
    | '/moderation'
    | '/my-questions'
    | '/notifications'
    | '/profile'
    | '/resources'
    | '/saved'
    | '/tasks'
    | '/questions/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  MentorsRoute: typeof MentorsRoute
  ModerationRoute: typeof ModerationRoute
  MyQuestionsRoute: typeof MyQuestionsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SavedRoute: typeof SavedRoute
  TasksRoute: typeof TasksRoute
  QuestionsQuestionIdRoute: typeof QuestionsQuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-questions': {
      id: '/my-questions'
      path: '/my-questions'
      fullPath: '/my-questions'
      preLoaderRoute: typeof MyQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId': {
      id: '/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof QuestionsQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  MentorsRoute: MentorsRoute,
  ModerationRoute: ModerationRoute,
  MyQuestionsRoute: MyQuestionsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SavedRoute: SavedRoute,
  TasksRoute: TasksRoute,
  QuestionsQuestionIdRoute: QuestionsQuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
